### ISSUE TITLE
Show only on mobile

### ISSUE THREAD

**Issue by soulvayne** [scotch-io/scotch-panels#18]
It would be great if i could disable it for desktop. I only want to show the panels on mobile.
Perhaps that could be mixed in with a issue that i also read here, the one that requested for brakepoints.

for example:

$('.scotch-panel').scotchPanel({
containerSelector: '#super-container',
distanceXS: '200px',
distanceSM: '300px',
distanceMD: false,
distanceLG: false
});

**Comment by kjprince** [comment]
I'm wondering how to change that `distance` option across screen sizes as well. Will report back if I find a reasonable solution.

**Comment by ncerminara** [comment]
Closing this per the "destroy" enhancement referenced here.
