### ISSUE TITLE
different widths for every CSS media break point?

### ISSUE THREAD

**Issue by cgarcia2595** [scotch-io/scotch-panels#19]
Is there a way to assign different widths for the off canvas navigation based on different CSS break points? 

Thank you

**Comment by Coedcoe** [comment]
i found a way to do this with javascript media queries
http://www.sitepoint.com/javascript-media-queries/

var mq = window.matchMedia( "(min-width: 500px)" );

if (mq.matches) {
  var side_menu = $('#sidemenu').scotchPanel({
      useCSS: false,
      containerSelector: 'body', // As a jQuery Selector
      direction: 'right', // Make it toggle in from the left
      duration: 50, // Speed in ms how fast you want it to be
      transition: 'ease', // CSS3 transition type: linear, ease, ease-in, ease-out, ease-in-out, cubic-bezier(P1x,P1y,P2x,P2y)
      clickSelector: '.open_sidemenu', // Enables toggling when clicking elements of this class
      distanceX: '20%', // Size fo the toggle
      enableEscapeKey: true
  });
}
else {
  var side_menu = $('#sidemenu').scotchPanel({
      useCSS: false,
      containerSelector: 'body', // As a jQuery Selector
      direction: 'right', // Make it toggle in from the left
      duration: 50, // Speed in ms how fast you want it to be
      transition: 'ease', // CSS3 transition type: linear, ease, ease-in, ease-out, ease-in-out, cubic-bezier(P1x,P1y,P2x,P2y)
      clickSelector: '.open_sidemenu', // Enables toggling when clicking elements of this class
      distanceX: '60%', // Size fo the toggle
      enableEscapeKey: true
  });
}

**Comment by cgarcia2595** [comment]
@ncerminara thank you very much, it works!
