### ISSUE TITLE
Fixed Header

### ISSUE THREAD

**Issue by rburch** [scotch-io/scotch-panels#22]
My site has a fixed header, for some reason installing the plugin makes it so my header isn't fixed anymore even though the css is still position fixed.

**Comment by ncerminara** [comment]
Check this out: https://github.com/scotch-io/scotch-panels/issues/7

Basically it's cause by a browser limitations with transforms. Switch the plugin to JS only or check these CSS work arounds:

- http://codepen.io/ncerminara/pen/Acybr
- http://codepen.io/ncerminara/pen/fwHjL 
- http://codepen.io/ncerminara/pen/rtesj
