### ISSUE TITLE
Scotch panels do not work when the containerSelector is not 'body'

### ISSUE THREAD

**Issue by atteeela** [scotch-io/scotch-panels#25]
Jquery 2.2.x,

**Comment by ncerminara** [comment]
Can you post a codepen?

**Comment by atteeela** [comment]
http://codepen.io/anon/pen/MYGEdZ
Notice 'super-parent' as the container.

**Comment by atteeela** [comment]
In my own code, I was able to get it to toggle, but I had to modify the code to set a height:100% to have the panel contents show up (otherwise height was 0)



           // DOM / CSS Changes / Make Things Happen
           var setup = function() {

            // Wrap the panel!
            var container = $(panel.settings.containerSelector);
            if (!container.hasClass('scotchified')) {
                container.wrapInner('<div class="scotch-panel-wrapper"><div class="scotch-panel-canvas"></div></div>').addClass('scotchified');
            }

            // Scotch Panel Wrapper CSS
            $('.scotch-panel-wrapper').css({
                'position': 'relative',
                'overflow': 'hidden',
                'width': '100%',
                'height': '100%' // Added by Atteeela to get it to show, otherwise height was 0
            });

**Comment by ncerminara** [comment]
Right, I saw the height was 0 too... Weird. Let me look into tonight and I'll get back to you.

**Comment by atteeela** [comment]
Thanks.

**Comment by ncerminara** [comment]
Super parent only wraps header. You need to wrap the entire contents:

Aka start at after <body> and end before </body>. 

Right now, super parent only wraps the panel - which is weird...
