### ISSUE TITLE
Scotch Panel makes overflow hidden

### ISSUE THREAD

**Issue by jhmacdon** [scotch-io/scotch-panels#26]
Is there a way to turn this off? It prevents scrolling on the entire page, not just the scotch panel. 

Or rather, it just prevents me from scrolling by putting everything into a <code>scotch-panel-canvas</code> and that is unscrollable unless I ADD overflow:auto, but this makes the scotch panel disappear and be replaced by a white screen.

**Comment by jhmacdon** [comment]
Update: it's the <code>scotch-panel-wrapper</code> that has a hidden overflow. Turning this off isn't favorable, but it allows scrolling and doesnt make the scotch panel disappear. I will keep working from here and update for others.

**Comment by ncerminara** [comment]
We have to use overflow hidden to create the effect unfortunately.
