### ISSUE TITLE
Fullscreen height menu

### ISSUE THREAD

**Issue by matcygan** [scotch-io/scotch-panels#28]
If content is lower than viewport there is no good way to fit menu to fullscreen height. 
forceMinHeight and minHeight does not work for this. 

I think it's connected to #26

**Comment by ncerminara** [comment]
So, the overflow is necessary for this method of off canvas. The easiest fix here, would be to take your largest container (which could be the scotch-wrapper) and simple apply:

```css
#my-container {
    min-height: 100vh;
}
```

You basically just need the container min-height to match the window min-height. This does it with CSS3, but you could also do it with JS.

**Comment by ncerminara** [comment]
Did this make sense? Reopen if you're still struffling.

**Comment by matcygan** [comment]
Thanks. Actually, it solves this problem.
I thought that these css units are much less supported by the browsers. A pleasant surprise :)
