### ISSUE TITLE
CDN Link?

### ISSUE THREAD

**Issue by RandomlyKnighted** [scotch-io/scotch-panels#29]
I know there was a CDN link for the last version of Scotch Panels. Any chance we can get one for the current and future versions?

**Comment by ncerminara** [comment]
https://cdn.rawgit.com/scotch-io/scotch-panels/master/dist/scotchPanels.min.js

**Comment by RandomlyKnighted** [comment]
Will that link remain same even with later versions?

**Comment by ncerminara** [comment]
That will always be the latest.

You can get versioned links like this: https://cdn.rawgit.com/scotch-io/scotch-panels/1.0.2/dist/scotchPanels.min.js
