### ISSUE TITLE
Mobile menu but also fixed. Is this possible?

### ISSUE THREAD

**Issue by WhirlyGuy** [scotch-io/scotch-panels#36]
Hi,

First of all, thank you so much for such an absolutely amazing plugin. This is truly fantastic.

I was wondering after looking at your demos though if it's somehow possible to merge two of them together?

These are the two demos I'm referring to :
https://panels.scotch.io/demos/side-menu-mobile-only-with-css/index.html
and
http://codepen.io/ncerminara/full/fwHjL

I'd really love to be able to have a menu which doesn't have the hamburger for desktop machines and then at a certain breakpoint / size then the hamburger menu comes in but I'd also like the header of the menu to be fixed at the top of the page.

Is that somehow easy to do by mixing those two examples together possibly?

Many thanks for any help with this.

Best wishes,

Mark

**Comment by ncerminara** [comment]
Closing this per: https://github.com/scotch-io/scotch-panels/issues/35
