### ISSUE TITLE
When using fixed navbar, menu content stays at `top` of screen

### ISSUE THREAD

**Issue by kjprince** [scotch-io/scotch-panels#37]
I'm using bootstrap and I've integrate the basic side panel similar to the one here: https://panels.scotch.io/

The problem I'm having is that I'm using a static header, so if the user scrolls down the page, then clicks the still visible "menu" button, they don't see the nav-items or any of the content as that stays at the top of the screen.

**Comment by ncerminara** [comment]
- http://codepen.io/ncerminara/pen/Acybr
- http://codepen.io/ncerminara/pen/fwHjL
- http://codepen.io/ncerminara/pen/rtesj

 Any of those help?

**Comment by ncerminara** [comment]
Closing but reopen if they don't!
