### ISSUE TITLE
Angular Library

### ISSUE THREAD

**Issue by waveminded** [scotch-io/scotch-panels#39]
It seems Scotch Panels don't place nice in Angular.  Is there an Angular version of the library?

**Comment by ncerminara** [comment]
Sorry, not at this time

**Comment by waveminded** [comment]
Has anyone got it to work inside of Angular?  We haven't been successful.

**Comment by ncerminara** [comment]
TBH it's a little weird that it breaks in Angular (this is just a jquery plugin). So maybe something else is going on...

This tutorial explains how the off-canvas is done: https://scotch.io/tutorials/off-canvas-menus-with-css3-transitions-and-transforms

Maybe you don't even need the plugin. All the plugin does is basically add a class that forces a CSS3 transform like in the tutorial above. (the plugin also has a JS fallback though).

You should be able to just toggle a class with ng-click and ng-class and force the animation with CSS

**Comment by ncerminara** [comment]
http://stackoverflow.com/questions/20460369/adding-and-removing-classes-in-angularjs-using-ng-click

**Comment by waveminded** [comment]
Awesome, thanks for the input!
