### ISSUE TITLE
Tutorial for the navbar on your main page?

### ISSUE THREAD

**Issue by Alex139602** [scotch-io/scotch-panels#40]
Hi there,

firstly i wanted to say thank you for creating this. without a doubt the best navbar menu and so flexible.

I wanted to ask if there is a tutorial or code example for the menu on panels.scotch.io? I'm creating a site and am using the plugin and absolutely love how the hamburger menu at the top switches to an X as the menu opens up. 

Thanks in advance.

**Comment by ncerminara** [comment]
Just search CodePen for working samples: http://codepen.io/search?q=hamburger+menu&limit=all&depth=everything&show_forks=false

I just built that from scratch

**Comment by Alex139602** [comment]
this works great, thank you so much!
