### ISSUE TITLE
Clickable overlay to close a panel?

### ISSUE THREAD

**Issue by Jakobud** [scotch-io/scotch-panels#6]
Trying to figure out how to use the `scotch-panel-canvas` to close a panel. 

Right now, I have two panels. One on the left side of my screen and one on the right. I have a menu button for each panel, one on the left and one on the right.

I tried adding `.scotch-panel-canvas` as another click selector, but there are two problems. 1. I only want to use it to close the panel. Not open it. And 2. Since I have two panels, when one panel is open and I click the `scotch-panel-canvas` it closes the open panel but also immediately opens the other panel.

Any clue on how to do what I'm looking for here?

Excellent script, btw. Nicest off canvas panel plugin I have seen by far.

**Comment by timkelty** [comment]
If you don't care about actually having an overlay and just want to close the menu when you click off of the open menu, this works for me:
```js
    $('.scotch-panel-canvas').on('click', function(event) {

      if ($(this).is('.scotch-is-showing')) {
        event.preventDefault();
        $mainNav.close();
      }
    });
```
