### ISSUE TITLE
Makes fixed navbar non-fixed

### ISSUE THREAD

**Issue by Jakobud** [scotch-io/scotch-panels#7]
Take a look at this code pen:

http://codepen.io/anon/pen/CazBH

The menu up top is fixed position. You can see as you scroll down the page.

Once you press the button to open the scotch panel, the navbar is no longer fixed. This is because the `.scotch-panel-canvas` container has 

```
 -webkit-transform: translate3d(0px, 0px, 0px);
transform: translate3d(0px, 0px, 0px);
```

added to it. If those styles are removed, then the navbar becomes fixed again.

**Comment by feesh** [comment]
Hi there! Noticed this issue still happens for non-mobile view for some reason even though I've added the useCSS: false flag —

![screen shot 2015-06-18 at 3 01 32 pm](https://cloud.githubusercontent.com/assets/453474/8243387/7c0ece70-15cb-11e5-9471-2ababd487a14.png)

— shows up while the browser width is > 600px.

**Comment by feesh** [comment]
Oh just kidding, I forgot that was in the CSS for the panel on my end. Maybe make a note about this in the tutorial here: https://panels.scotch.io/demos/side-menu-mobile-only-with-css/index.html ?

**Comment by pjldesign** [comment]
Used the API Callbacks to remove the transform and removed completely from plugin (kind of hacky, but...):

    $('#mypanel').scotchPanel({
    useCSS: true,
    containerSelector: 'body',
    direction: 'top',
    duration: 300,
    transition: 'ease',
    clickSelector: '.searchBtn',
    distanceX: '70%',
    enableEscapeKey: true,
    beforePanelOpen: function() {
          $('.scotch-panel-canvas').css({
                    '-moz-transform': 'translate3d(0, 0, 0)',
                    '-ms-transform': 'translate3d(0, 0, 0)',
                    '-o-transform': 'translate3d(0, 0, 0)',
                    '-webkit-transform': 'translate3d(0, 0, 0)',
                    'transform': 'translate3d(0, 0, 0)'
          });
          $("html, body").animate({ scrollTop: 0 }, "slow");
          return false;
        },
    afterPanelClose: function() {
            $('.scotch-panel-canvas').css({
                    '-moz-transform': '',
                    '-ms-transform': '',
                    '-o-transform': '',
                    '-webkit-transform': '',
                    'transform': ''
          });
        }
    });

**Comment by jontarbuck** [comment]
Trying to fix the position fixed issue myself, not having any luck with getting the above method working in Chrome - my fixed position div isn't fixed - any help would be appreciated!
